spring.application.name=sistemaiglesia

# --- CONEXIÓN LOCAL (APAGADA PARA LA PRESENTACIÓN) ---
# spring.datasource.url=jdbc:postgresql://localhost:5432/iglesia_db
# spring.datasource.username=postgres
# spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Formatea el SQL en la consola para que sea legible
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURACIÓN DE CORREO (GMAIL SMTP)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Pon aquí tu correo personal de prueba:
spring.mail.username=iglesiadelacalle413@gmail.com
# Pon aquí la contraseña de 16 letras que te dio Google (sin espacios):
spring.mail.password=vcquaapknipztdnd

# Configuraciones de seguridad obligatorias de Google
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Desactivar caché de Thymeleaf para ver cambios en HTML al instante
spring.thymeleaf.cache=false

# Opcional: Desactivar caché de archivos estáticos (JS, CSS)
spring.web.resources.cache.period=0

# ==========================================
# --- CONEXIÓN A LA NUBE (NEON.TECH) ACTIVA ---
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-wispy-hill-anxo7i38.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NfaVW7hDp8cz

# --- CONFIGURACIÓN DE HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true